# サービス検索＿共通
class OsakaCity < ActiveHash::Base
  include ActiveHash::Associations
  has_many :ghs

  self.data = [
    { id: 1, name: '大阪市旭区' },
    { id: 2, name: '大阪市阿倍野区' },
    { id: 3, name: '大阪市生野区' },
    { id: 4, name: '大阪市北区' },
    { id: 5, name: '大阪市此区' },
    { id: 6, name: '大阪市城東区' },
    { id: 7, name: '大阪市住之江区' },
    { id: 8, name: '大阪市住吉区' },
    { id: 9, name: '大阪市大正区' },
    { id: 10, name: '大阪市中央区' },
    { id: 11, name: '大阪市鶴見区' },
    { id: 12, name: '大阪市天王寺区' },
    { id: 13, name: '大阪市浪速区' },
    { id: 14, name: '大阪市西区' },
    { id: 15, name: '大阪市西成区' },
    { id: 16, name: '大阪市西淀川区' },
    { id: 17, name: '大阪市東住吉区' },
    { id: 18, name: '大阪市東成区' },
    { id: 19, name: '大阪市東淀川区' },
    { id: 20, name: '大阪市平野区' },
    { id: 21, name: '大阪市福島区' },
    { id: 22, name: '大阪市港区' },
    { id: 23, name: '大阪市都島区' },
    { id: 24, name: '大阪市淀川区' },
    { id: 25, name: '堺市堺区' },
    { id: 26, name: '堺市中区' },
    { id: 27, name: '堺市東区' },
    { id: 28, name: '堺市西区' },
    { id: 29, name: '堺市南区' },
    { id: 30, name: '堺市北区' },
    { id: 31, name: '堺市美原区' },
    { id: 32, name: '池田市' },
    { id: 33, name: '和泉市' },
    { id: 34, name: '泉大津市' },
    { id: 35, name: '泉佐野市' },
    { id: 36, name: '茨木市' },
    { id: 37, name: '大阪挟山市' },
    { id: 38, name: '貝塚市' },
    { id: 39, name: '柏原市' },
    { id: 40, name: '交野市' },
    { id: 41, name: '門真市' },
    { id: 42, name: '河南町' },
    { id: 43, name: '河内長野市' },
    { id: 44, name: '岸和田市' },
    { id: 45, name: '熊取町' },
    { id: 46, name: '四條畷市' },
    { id: 47, name: '島本町' },
    { id: 48, name: '吹田市' },
    { id: 49, name: '摂津市' },
    { id: 50, name: '泉南市' },
    { id: 51, name: '太子町' },
    { id: 52, name: '大東市' },
    { id: 53, name: '高石市' },
    { id: 54, name: '高槻市' },
    { id: 55, name: '田尻町' },
    { id: 56, name: '忠岡町' },
    { id: 57, name: '千早赤阪村' },
    { id: 58, name: '豊中市' },
    { id: 59, name: '豊能町' },
    { id: 60, name: '豊田林市' },
    { id: 61, name: '寝屋川市' },
    { id: 62, name: '能勢町' },
    { id: 63, name: '羽曳野市' },
    { id: 64, name: '阪南市' },
    { id: 65, name: '東大阪市' },
    { id: 66, name: '枚方市' },
    { id: 67, name: '藤井寺市' },
    { id: 68, name: '松原市' },
    { id: 69, name: '岬町' },
    { id: 70, name: '箕面市' },
    { id: 71, name: '守口市' },
    { id: 72, name: '八尾市' }
  ]
end
